Image: kubespark/spark-driver:v2.1.0-kubernetes-0.3.1
pullPolicy: IfNotPresent
master:
  replicaCount: 1
  service:
    sparkExtPort: 7077
    sparkIntPort: 7077
    webuiExtPort: 8080
    webuiIntPort: 8080
    protocol: TCP
worker:
  replicaCount: 3
  service:
    sparkExtPort: 7078
    sparkIntPort: 7078
    protocol: TCP
